### ISSUE TITLE
suggestion for expressive eyes option

### ISSUE THREAD

**Issue by thomasjoubert** [ccappetta/bidirectional_streaming_ai_voice#3]
Hi! 
I know this is not directly the goal of this project, but I have been struggling to adapt the code to do this, and maybe it'd be of interest to some.

I've seen that on your videos, there is an effect of border moving while Claude is talking around the avatar.
I was willing to have a more "immersive" animation like the one you have on chatGPT app (the dots moving along the volume of the voice).

What I've been attempting to do for a while as a non coder is to have expressive eyes, like Eve in Wall-e movie, depending on the feeling Claude is expressing. Your code seems to be compatible with that because it chunks the elevenlabs answers.
We would have a flask server with a page accepting request, displaying normal eyes.

Here is my plan :
1-Instruct Claude to answer like it would be adding emojis before every paragraphe depending on the feeling it want to express
2-Parse the chunks of the answer for every emoji (instead of ., !, ?)
3-Send the chunk to eleven labs (without the emoji) and stream the voice
4-Send a post request to change the displayed feeling on the page
Back to 3

**Comment by ccappetta** [comment]
Hey mate, love the idea! A couple thoughts - the tool I'm using to record the video is OBS and it's open source so you might be able to find or build a mechanism to call into OBS and modify the display rather than a separate flask page? 

I'm not sure, I've not done anything custom with OBS but I know it's super versatile and people have done tons of wild stuff. It does look like OBS has a python library that could probably turn different filters on and off https://docs.obsproject.com/scripting

Conversely a much lower hanging angle would be to give it a lot of expressiveness and different visuals via the OBS sound-triggered filters (which is what I'm using in a very rudimentary way for the border pulsing effect). It wouldn't be directly matching the content to the expression but could still have quite a lot of variety I think. [This was the video ](https://youtu.be/vsRlOkyVqU4?si=wCAS26abCiSUp_jZ) where I found out about that volume-based approach but I think there are a lot of streamers out there with implementations of varying complexity and quality. A couple search terms that might lead to good resources are vtuber and virtual avatar. Hope you can find something sweet to fit the goal I think it sounds awesome!

**Comment by thomasjoubert** [comment]
That's cool! I think it's doable with the websocket obs plugin to change scene depending on feeling. I'll try a mockup version, I'm just unsure about where to put the request at the right time in your code so that expression matches what's currently being said :)

**Comment by ccappetta** [comment]
hah yea that would be the tricky bit, i think you'd potentially want some logic in the async_tasks.py `async def process_text_to_speech():` function perhaps reviewing the text variable being passed in? That's the bit thats sending chunks of claude's text off to elevenlabs for text-to-speech, and probably the best place to review the 'current-ish' content. Claude could be instructed to use 5 or so different *emotion* keywords and then perhaps some logic in that function could be what identifies the appropriate keyword and sends it off to OBS to change the visual filter. I think as it gets toward the end of the reply though that may get more and more out of sync with the words because my hunch is the audio transcription (and thereby hypothetical emote review) for the whole claude reply is probably done by the time the audio playback is maybe halfway done. Maybe there's another angle with more time-based tracking and visual-handling... perhaps with some logic to track how long each chunk is and let the script know when a  given chunk is beginning to be played? Its a super nifty angle.

**Comment by ccappetta** [comment]
big round of closing comments for my own organizational sanity, please shout to continue this convo!
