### ISSUE TITLE
Using another LLM instead of Claude 

### ISSUE THREAD

**Issue by jbdatascience** [ccappetta/bidirectional_streaming_ai_voice#5]
I would like to use another LLM in this amazing application instead of Anthropic Claude.

I was thinking about Mixtral-8x7b-Groq as a LLM which has an insanely fast inference (because it runs in the cloud on specialized hardware, namely LPUs, Language Processing Units). Furthermore its intelligence is quite good I think.

So how would I have to change the code so that it uses Mixtral-8x7b-Groq as a LLM?

**Comment by ccappetta** [comment]
I think it would have some bits and bobs to update in a number of places that would become clear only once you started running tests and getting errors, but the main portion handling the llm calls is the def generate_and_process_text specifically:

```     
with client.messages.stream(
        max_tokens=1024,
        messages=validated_history,
        system=system_message,
        model="claude-3-opus-20240229",
    ) as stream:
        for text in stream.text_stream:
            print(Fore.CYAN + text + Style.RESET_ALL, end="", flush=True)
            claude_response += text
            buffer += text

            # Check if buffer is ready to be chunked
            last_splitter_pos = max(buffer.rfind(splitter)
                                    for splitter in splitters)
            if len(buffer) >= min_chunk_size and last_splitter_pos != -1:
                chunk = buffer[:last_splitter_pos+1]
                buffer = buffer[last_splitter_pos+1:]

                # Queue this chunk for async TTS processing
                queue_chunk_for_processing(chunk)
```
that client is the anthropic LLM and would be swapped in with something like a call to another api or into a local model. I would love to see a local mixtral version of this from a token cost perspective! I think an LLM aspect that would really have potential gains would be in whatever LLM can begin streaming the tokens fastest... not necessarily the ones that finish replying fastest. I say that because once the downstream audio gets generating and playing the token streaming of even Claude opus is coming in faster than the voice audio is playing... so its just that first fewseconds between prompting the LLM and being able to get a usable streamed chunk of tokens sent over to elevenlabs would be the performance gain. I've actually just put some more thoughts on latency considerations at the bottom of the readme. 

Thanks for the commend i love the idea of running a local LLM with this! And actually I think it would be sweet to replace elevenlabs with a local RVC implementation as well. It could be "Quill in a box".

Happy to chat more about it and I'll leave the issue open for awhile for further conversation or anyone else wanting to weigh in!

**Comment by ccappetta** [comment]
big round of closing comments for my own organizational sanity, please shout to continue this convo!
